# Generated by Django 4.1.2 on 2022-10-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_post_summarized_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='twtpost',
            field=models.BooleanField(default=False),
        ),
    ]
